# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    update_android_strings(
      xml_path: "app/src/main/res/values/strings.xml",
      block: lambda { |strings|
			# value must be a string, you can update what you want here.
        strings['app_name'] = "Beta Demo Application"
        #strings['b'] = "string keys"
        #strings['c'] = "string keys"
      }
    )
    gradle(
      task: "clean assembleRelease",
      properties: {
        "android.injected.signing.store.file" => "examplestore",
        "android.injected.signing.store.password" => "123456",
        "android.injected.signing.key.alias" => "signFiles",
        "android.injected.signing.key.password" => "123456",
        "applicationId": "com.anko.demoapp.beta",
        "versionName": "2.0",
        "buildNumber": "10"
      }
    )
    
    appcenter_upload(
      api_token: "83683087f9c8c0fdb4cf00f09e0dc108b2bdbfbb",
      owner_name: "lisavod",
      owner_type: "user", # Default is user - set to organization for appcenter organizations
      app_name: "sadov-demo-android",
      file: "app/build/outputs/apk/release/app-release.apk",
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
